@startuml

class InventoryTracker {
    start()
    main()
}


class MainControl{
    ItemModel()
    MainWinowControl(ItemModel, SceneManager)
    'constructor
    addItemButtonClick(EventHandler)
    editItemButtonClick(EventHandler)
    removeItemButtonClick(EventHandler)

    addItem(String, String, Double)
    editItem(String, String, Double)
    remvoveItem(String, String, Double)
}


class itemModel{
    ObservableList <Item>
}

class Item{
    name : SimpleStringProperty
    serialNumber : SimpleStringProperty
    value : SimpleDoubleProperty

    .getName()
    .setName()
    .nameProperty

    ....
}
openjfx.org.Application <|-- InventoryTracker
InventoryTracker -- MainControl
MainControl -- itemModel
itemModel *-- Item
@enduml